{% set name = "dem2mesh" %}
{% set version = "master" %}
{% set commit = "1de2f3dfc6e8966b176fc198f4e21183b59951c5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/OpenDroneMap/dem2mesh/archive/{{ commit }}.tar.gz
  sha256: fcc1645927adf473a7dced7153b10eaf7dd9f1c623d2d7dc5f34d0cf05979e21

build:
    number: 0

requirements:
  build:
    # - {{ compiler("c") }}
    # - {{ compiler("cxx") }}
    - cmake
    # - ninja
  host:
    - libgdal {{ libgdal }}

test:
  commands:
    - test -f $PREFIX/bin/dem2mesh

about:
  home: https://github.com/OpenDroneMap/dem2mesh
  license: GPL 3
  summary: Quickly generate 2.5D meshes from elevation models.

extra:
  recipe-maintainers:
    - v-turin
